import {Component} from '@angular/core';

@Component({
  selector: 'app-landing-page',
  template: `
    <div class="container">
      <div class="starter-template">
        <h1>Angular CLI + Bootstrap</h1>
        <p class="lead">This tutorial shows how to use Bootstrap and Font Awesome with an app generated by Angular CLI.</p>
      </div>
    </div>
  `,
  styles: [`
    .starter-template {
      padding: 3rem 1.5rem;
      text-align: center;
    }
  `]
})
export class LandingPageComponent {

}
